# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created: Tue Apr  7 11:59:55 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(760, 644)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/logo/aa_logobasic_4c.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(200000, 200000))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton1_0 = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton1_0.setFont(font)
        self.pushButton1_0.setObjectName(_fromUtf8("pushButton1_0"))
        self.gridLayout.addWidget(self.pushButton1_0, 0, 2, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.pushButton1_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton1_2.setObjectName(_fromUtf8("pushButton1_2"))
        self.gridLayout.addWidget(self.pushButton1_2, 0, 4, 1, 1)
        self.pushButton2_0 = QtGui.QPushButton(self.centralwidget)
        self.pushButton2_0.setObjectName(_fromUtf8("pushButton2_0"))
        self.gridLayout.addWidget(self.pushButton2_0, 1, 2, 1, 1)
        self.pushButton3_0 = QtGui.QPushButton(self.centralwidget)
        self.pushButton3_0.setObjectName(_fromUtf8("pushButton3_0"))
        self.gridLayout.addWidget(self.pushButton3_0, 2, 2, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_1 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_1.setText(_fromUtf8(""))
        self.lineEdit_1.setObjectName(_fromUtf8("lineEdit_1"))
        self.gridLayout.addWidget(self.lineEdit_1, 0, 1, 1, 1)
        self.pushButton1_1 = QtGui.QPushButton(self.centralwidget)
        self.pushButton1_1.setObjectName(_fromUtf8("pushButton1_1"))
        self.gridLayout.addWidget(self.pushButton1_1, 0, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.pushButton2_1 = QtGui.QPushButton(self.centralwidget)
        self.pushButton2_1.setObjectName(_fromUtf8("pushButton2_1"))
        self.gridLayout.addWidget(self.pushButton2_1, 1, 3, 1, 1)
        self.pushButton2_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton2_2.setObjectName(_fromUtf8("pushButton2_2"))
        self.gridLayout.addWidget(self.pushButton2_2, 1, 4, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 5, 0, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout.addWidget(self.lineEdit_5, 5, 1, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout.addWidget(self.lineEdit_4, 4, 1, 1, 1)
        self.pushButton3_1 = QtGui.QPushButton(self.centralwidget)
        self.pushButton3_1.setObjectName(_fromUtf8("pushButton3_1"))
        self.gridLayout.addWidget(self.pushButton3_1, 2, 3, 1, 1)
        self.pushButton5_0 = QtGui.QPushButton(self.centralwidget)
        self.pushButton5_0.setObjectName(_fromUtf8("pushButton5_0"))
        self.gridLayout.addWidget(self.pushButton5_0, 5, 2, 1, 1)
        self.pushButton4_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton4_2.setObjectName(_fromUtf8("pushButton4_2"))
        self.gridLayout.addWidget(self.pushButton4_2, 3, 4, 2, 1)
        self.pushButton4_1 = QtGui.QPushButton(self.centralwidget)
        self.pushButton4_1.setObjectName(_fromUtf8("pushButton4_1"))
        self.gridLayout.addWidget(self.pushButton4_1, 3, 3, 2, 1)
        self.pushButton5_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton5_2.setObjectName(_fromUtf8("pushButton5_2"))
        self.gridLayout.addWidget(self.pushButton5_2, 5, 4, 1, 1)
        self.pushButton5_1 = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton5_1.setFont(font)
        self.pushButton5_1.setObjectName(_fromUtf8("pushButton5_1"))
        self.gridLayout.addWidget(self.pushButton5_1, 5, 3, 1, 1)
        self.pushButton3_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton3_2.setObjectName(_fromUtf8("pushButton3_2"))
        self.gridLayout.addWidget(self.pushButton3_2, 2, 4, 1, 1)
        self.pushButton4_0 = QtGui.QPushButton(self.centralwidget)
        self.pushButton4_0.setObjectName(_fromUtf8("pushButton4_0"))
        self.gridLayout.addWidget(self.pushButton4_0, 3, 2, 2, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 3, 0, 2, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/bio.sqrc/Sequencing.jpg")))
        self.label_5.setScaledContents(True)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.textEdit_original_model = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_original_model.setEnabled(True)
        self.textEdit_original_model.setReadOnly(True)
        self.textEdit_original_model.setObjectName(_fromUtf8("textEdit_original_model"))
        self.gridLayout_2.addWidget(self.textEdit_original_model, 1, 0, 1, 1)
        self.textEdit_refined_model = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_refined_model.setReadOnly(True)
        self.textEdit_refined_model.setObjectName(_fromUtf8("textEdit_refined_model"))
        self.gridLayout_2.addWidget(self.textEdit_refined_model, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.LogText)
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_2.addWidget(self.label_10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_1, self.pushButton1_0)
        MainWindow.setTabOrder(self.pushButton1_0, self.pushButton1_1)
        MainWindow.setTabOrder(self.pushButton1_1, self.pushButton1_2)
        MainWindow.setTabOrder(self.pushButton1_2, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.pushButton2_0)
        MainWindow.setTabOrder(self.pushButton2_0, self.pushButton2_1)
        MainWindow.setTabOrder(self.pushButton2_1, self.pushButton2_2)
        MainWindow.setTabOrder(self.pushButton2_2, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.pushButton3_0)
        MainWindow.setTabOrder(self.pushButton3_0, self.pushButton3_1)
        MainWindow.setTabOrder(self.pushButton3_1, self.pushButton3_2)
        MainWindow.setTabOrder(self.pushButton3_2, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.pushButton4_0)
        MainWindow.setTabOrder(self.pushButton4_0, self.pushButton4_1)
        MainWindow.setTabOrder(self.pushButton4_1, self.pushButton4_2)
        MainWindow.setTabOrder(self.pushButton4_2, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.pushButton5_0)
        MainWindow.setTabOrder(self.pushButton5_0, self.pushButton5_1)
        MainWindow.setTabOrder(self.pushButton5_1, self.pushButton5_2)
        MainWindow.setTabOrder(self.pushButton5_2, self.textEdit_original_model)
        MainWindow.setTabOrder(self.textEdit_original_model, self.textEdit_refined_model)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Bioinformatic", None))
        self.label.setText(_translate("MainWindow", "Structural Model Refinement", None))
        self.pushButton1_0.setText(_translate("MainWindow", "Display", None))
        self.lineEdit_3.setText(_translate("MainWindow", "Atomic_refinement.xml", None))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", ".XML", None))
        self.pushButton1_2.setText(_translate("MainWindow", "View", None))
        self.pushButton2_0.setText(_translate("MainWindow", "Generate", None))
        self.pushButton3_0.setText(_translate("MainWindow", "Generate", None))
        self.lineEdit_2.setText(_translate("MainWindow", "Species.xml", None))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", ".XML", None))
        self.lineEdit_1.setPlaceholderText(_translate("MainWindow", ".SBML", None))
        self.pushButton1_1.setText(_translate("MainWindow", "Edit", None))
        self.label_14.setText(_translate("MainWindow", "Species", None))
        self.pushButton2_1.setText(_translate("MainWindow", "Edit", None))
        self.pushButton2_2.setText(_translate("MainWindow", "View", None))
        self.label_11.setText(_translate("MainWindow", "Atomic refinement", None))
        self.label_13.setText(_translate("MainWindow", "Refined model", None))
        self.lineEdit_5.setText(_translate("MainWindow", "Refined_model.sbml", None))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", ".SBML", None))
        self.lineEdit_4.setText(_translate("MainWindow", "Complex_refinement.xml", None))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", ".XML", None))
        self.pushButton3_1.setText(_translate("MainWindow", "Edit", None))
        self.pushButton5_0.setText(_translate("MainWindow", "Generate", None))
        self.pushButton4_2.setText(_translate("MainWindow", "View", None))
        self.pushButton4_1.setText(_translate("MainWindow", "Edit", None))
        self.pushButton5_2.setText(_translate("MainWindow", "View", None))
        self.pushButton5_1.setText(_translate("MainWindow", "Display", None))
        self.pushButton3_2.setText(_translate("MainWindow", "View", None))
        self.pushButton4_0.setText(_translate("MainWindow", "Generate", None))
        self.label_2.setText(_translate("MainWindow", "Initial model", None))
        self.label_12.setText(_translate("MainWindow", "Complex refinement", None))
        self.label_3.setText(_translate("MainWindow", "Original model", None))
        self.label_4.setText(_translate("MainWindow", "Refined model", None))
        self.label_10.setText(_translate("MainWindow", "Copyrights@Computational Biomodelling Laboratory", None))

